.eslintrc.js, package-lock.json, package.json
=> [HHH - 2] 초기 eslint rules 설정

package-lock.json, package.json, src/components/SplitLayout.js, src/store.js
- prop-types, styled-components 설치
- SplitLayout 컴포넌트에 필요한 styled component 추가
- prop types validation 적용
=> [HHH - 4] SplitLayout component 추가

src/components/App.jsx, src/components/CampaignForm.jsx, src/components/Card.jsx, src/pages/CreateCampaign.jsx
- Card component
- CampaignForm component
- CreateCampaign page
추가했습니다.
나중에 백엔드에서 input validation에 사용한 Joi schema 가져와서 그대로 form validation에 사용할 예정입니다.
=> [HHH - 7] CreateCampaign 페이지 추가

public/index.html, src/apis/payment.js, src/components/CampaignForm.jsx, src/pages/CreateCampaign.jsx
=> [HHH - 7] payment API 연결

src/components/RegisterForm.jsx, src/pages/RegisterPage.jsx
- passwordConfirm도 submit하도록 RegisterForm 수정
- RegisterForm에서 form values를 react-hook-form을 통해 uncontrolled 방식으로 관리하도록 수정
=> [HHH - 10] RegisterForm 수정

public/index.css, public/index.html, src/components/Modal.jsx, src/components/ModalContent.jsx
- createPortal을 이용하여 Modal이 부모 컴포넌트의 DOM 계층 구조 바깥에 있는 DOM 노드로 렌더링
- 모달의 메시지와 버튼을 포함하는 ModalContent 추가
- styled-components 및 css 추가
=> [HHH - 11] Modal component 추가 

src/components/CampaignForm.jsx, src/components/LoginForm.jsx, src/components/RegisterForm.jsx, src/constants/validationErrorMessage.js
- react-hook-form과 joi를 이용한 input validation
- RegisterForm input validation
- LoginForm input validation
- CampaignForm input validation
- validation error message 상수 추가
=> [HHH - 13] Input validation 추가

package-lock.json, package.json, public/index.css, src/components/DashboardNav.jsx
- useSelector을 이용해서 redux store의 state를 가져와서 렌더링함
- 맨 왼쪽 상단의 로고를 클릭하면 홈으로 이동
=> [HHH - 14] DashboardNav 컴포넌트 추가

public/index.css, src/components/ModalContent.jsx
- Modal의 css를 styled-components로 수정
=> [HHH - 15] Modal css 수정

src/components/DashboardMain.jsx
- Dashboard nav에서 선택된 campaign의 data중 오늘 데이터를 추출 가능하도록 수정
=> [HHH - 17] Dashboard nav에서 선택된 campaign의 data중 오늘 데이터를 추출 가능하도록 수정

package-lock.json, package.json, src/components/DashboardMain.jsx
- 도달, 클릭, CTR, CPC, 등을 확인 가능한 chart 추가
=> [HHH - 18] Dashboard chart 추가

package-lock.json, src/apis/image.js, src/components/CampaignForm.jsx, src/pages/CreateCampaign.jsx
- fetchImageFile API 추가
- 사용자가 등록한 image파일의 url을 서버로 요청
=> [HHH - 19] CampaignForm의 이미지 업로딩 기능 추가

src/components/CampaignForm.jsx
- 일일 예산(watchDailyBudget)과 정해진 퍼센트에 따라 일일 추산 결과(도달수, 클릭수)를 보여주는 기능 추가
=> [HHH - 21] CampaignForm 컴포넌트에 일일 추산 결과를 보여주는 기능 추가

src/components/ADPreviewModal.jsx, src/components/CampaignForm.jsx, src/components/DashboardMain.jsx, src/components/DashboardNav.jsx, src/components/ModalContent.jsx, src/css/color.js, src/pages/CreateCampaign.jsx, src/utils/index.js
- 광고 예시 미리보기 modal css 추가
- Invisible input 삭제
- 배너 이미지 용량 제한 util 함수 추가
=> [HHH - 24] Modal css 추가, 이미지 url input 삭제

package-lock.json, src/apis/campaigns.js, src/components/CampaignForm.jsx, src/pages/CreateCampaign.jsx, src/reducers/estimate.js, src/reducers/index.js, src/reducers/target.js
- fetchEstimate api 추가
- estimate reducer 추가
- 캠패인 생성 폼에 타겟 설정하기 카드 추가(input: gender, age, country)
- 타겟 정보 핸들링 함수 추가
=> [HHH - 27] 캠패인 생성 타겟 설정하기 기능 추가

src/components/DashboardMain.jsx, src/reducers/campaigns.js
- overview에 cpm 추가
- 인구통계 및 지역별 데이터 들어갈 자리 추가
=> [HHH - 29] Dashboard 추가 항목 setting

src/components/CampaignForm.jsx, src/components/Card.jsx, src/constants/countries.js, src/reducers/campaigns.js, src/reducers/estimate.js, src/styles/theme.js
- CampaignForm 컴포넌트의 CSS 전반적으로 정리
=> [HHH - 31] CampaignForm 컴포넌트에 CSS 추가

package-lock.json, package.json, public/index.css, src/components/App.jsx, src/components/DashboardMain.jsx, src/components/MapChart.jsx, src/pages/Dashboard.jsx
- 대시보드에 세계지도 추가
- 대시보드에 캠페인 타겟 view 추가
- 대시보드에 결제버튼 추가
=> [HHH - 32] 대시보드에 차트, 결제버튼 추가

package-lock.json, public/index.css, src/components/App.jsx, src/components/Header.jsx, src/components/LoginForm.jsx, src/components/SplitLayout.jsx, src/reducers/user.js, src/utils/index.js
- LoginForm 컴포넌트의 CSS 수정
- Login시 / 페이지가 아닌 /main 페이지로 이동하도록 리액트 라우터 수정
=> [HHH - 32] LoginForm 컴포넌트의 CSS 수정

package-lock.json, public/index.css, public/index.html, src/components/CampaignForm.jsx, src/components/DashboardMain.jsx, src/components/Header.jsx, src/pages/CreateCampaign.jsx, src/pages/Dashboard.jsx
=> [HHH - 37] CSS 수정

package-lock.json, src/pages/DownloadHome.jsx
=> [HHH -40] Flexilis 앱 다운로드 환경변수 추가

README.md
=> [HHH - 43] 초기 README 작성

src/components/DashboardMain/index.jsx, src/components/DashboardMain/styles.js, src/components/Overview/index.jsx, src/components/Overview/styles.js, src/components/Target/index.jsx, src/components/Target/styles.js, src/constants/age.js, src/constants/gender.js, src/constants/overviewTypes.js, src/constants/paymentResultMessage.js, src/constants/paymentStatus.js, src/styles/theme.js, src/utils/customizeGraphAxisTick.js, src/utils/formatGraphTick.js, src/utils/getOverviewData.js, src/utils/sortByCountry.js
- DashboardMain 컴포넌트에서 Target, Overview 컴포넌트 분리
- 대시보드 관련 상수 및 유틸 함수 추가
=> [HHH - 45] DashboardMain 리펙토링
